### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by pindab0ter** [TheBrutalX/Factorio-mod-uploader-action#18]
In this run I ran into `Request failed with status code 400`, however, the body of the response is not shown, so I cannot tell what exactly went wrong.

Please add support for showing the body on a >= 400 response.

https://github.com/pindab0ter/sorted-logistic-sections/actions/runs/12213348246/job/34072854011#step:5:12

**Comment by TheBrutalX** [comment]
Hi, 
i've added the stack propagation and make a better error handling for the Factorio Api Service, i planned the adding this for the next release,

**Comment by pindab0ter** [comment]
Awesome. Thank you!

For anyone that came across this error: In my case it was because I accidentally used the "Token" found in the Profile page, instead of an API key which you can find further down that page.
