### ISSUE TITLE
unwanted files in created zip file

### ISSUE THREAD

**Issue by xyzzycgn** [TheBrutalX/Factorio-mod-uploader-action#33]
I was expecting that the purpose for file  _.factorioignore_  is to prevent unwanted contents from being added to the zip. For the files created by clion (.idea/ and *.iml) or the .gitignore this seems to work - unfortunately not for the folders  .git and .github. 

This is my .factorioignore

```
.git
.github
.gitignore
.log
.tmp
.vscode
*.bak
*.tmp
*.tmp.*
.idea
*.iml
.factorioignore
```

I've seen that .factorioignore is only mentioned in your wiki under [upload](https://github.com/TheBrutalX/Factorio-mod-uploader-action/wiki/Avaible-Actions#action-upload) - is this really correct?

P.S.: v2 works fine - i've just created and uploaded a new version of my mod without any problems (except that mentioned above 😉)

**Comment by TheBrutalX** [comment]
Hi, yes I haven't had time yet to update the Wiki after the release, later I'll give it a try with your .factorioignore file and see what could be the problem


I am glad to hear that V2 (apart from this bug) behaved well.

**Comment by xyzzycgn** [comment]
In the meantime I thought, that the reason might be that your _FactorioIgnoreParser_ expects that patterns for directories must end with / - as seen in the _setDefaultPatterns()_ method - but what really confuses me is that .idea uses no / too, but is not included - really weird 🤔

**Comment by xyzzycgn** [comment]
Just figured out what makes the difference between .idea/ vs. .git/ or .github/ - .idea/ is in the .gitignore and thus not present when running the action. 

And I think .git/ and .github/ are included because my .factorioignore doesn't contain the / at the end - as the code IMO expects - and that's why _isDirectory_ isn't set in _IFactorioIgnoreRule_.

**Comment by TheBrutalX** [comment]
These days I am rewriting that class. 
I added tests for many cases and reached 90% coverage
before releasing it I need a few more days that besides doing unit tests I want to have time to try it in the pratical

**Comment by xyzzycgn** [comment]
No reason to rush - was able to verify (with [https://github.com/nektos/act](https://github.com/nektos/act)) that adding / to the offending patterns eliminates the problem, so that I have a nice workaround

**Comment by TheBrutalX** [comment]
Hi, I tested with act the refactor of FactorioIgnoreParser class and everything seems to work correctly

I also created the [Wiki](https://github.com/TheBrutalX/Factorio-mod-uploader-action/wiki/.factorioignore) for the .factorioignore file 

I release 2.0.1 and close the issue 
#35
