### ISSUE TITLE
V2 fails due to missing file(s)

### ISSUE THREAD

**Issue by xyzzycgn** [TheBrutalX/Factorio-mod-uploader-action#37]
Your new release unfortunately is broken .

![grafik](https://github.com/user-attachments/assets/02507c6f-7fab-4214-bc3d-01bc2961272f)

Could you please restore the previous release for v2 (I think you updated it when releasing 2.0.1)?

Thx

P.S.: I hope reusing the same version for the two releases was an accident - and not intentional

**Comment by TheBrutalX** [comment]
Fixed
