### ISSUE TITLE
Github action cannot be found due to missing version numbering in Readme example

### ISSUE THREAD

**Issue by JasonLandbridge** [TheBrutalX/Factorio-mod-uploader-action#7]
Hi there!

First off, awesome Github Action!

There is a bit of incorrect info in the readme it says to use the action like this:

`uses: TheBrutalX/factorio-mod-uploader-action`

This causes an error when running it:
`the uses' attribute must be a path, a Docker image, or owner/repo@ref`

It should be:
`uses: TheBrutalX/Factorio-mod-uploader-action@1.0.3`

then it does work as intended, however, ideally it should be something like this:

`uses: TheBrutalX/Factorio-mod-uploader-action@v1`

then you can make minor releases and everyone will use the latest stable version.

Anyway, thanks for the hard work!

**Comment by TheBrutalX** [comment]
Hi,
thank for your suggestion, i planned this to the next release.

I try to push the new release this tag on this weekend

**Comment by JasonLandbridge** [comment]
Many thanks, I can confirm it works now with `@v1`!

Maybe update the [Readme](https://github.com/TheBrutalX/Factorio-mod-uploader-action/blob/main/README.md) with this `@v1`?

**Comment by TheBrutalX** [comment]
Sure! I missed in the commit
