### ISSUE TITLE
Bad request when upload of factorio mod

### ISSUE THREAD

**Issue by JasonLandbridge** [TheBrutalX/Factorio-mod-uploader-action#8]
Hi there!

I seem to be getting a Bad request when the upload step happens: [Action being run](https://github.com/JasonLandbridge/CircuitHUD-V2/actions/runs/11741033490/job/32709113785)

[The workflow file](https://github.com/JasonLandbridge/CircuitHUD-V2/actions/runs/11741033490/workflow)

I have made sure to add `FACTORIO_API_KEY` under my secrets with a valid api-key

I tried looking trough the source code but couldn't find anything wrong.

Thanks!

**Comment by TheBrutalX** [comment]
Hi, i'm not sure about why, you added a new api key on https://factorio.com/profile?
![image](https://github.com/user-attachments/assets/2fbcf57a-5186-411a-a435-0b499487a835)

The Api key need this usage
![image](https://github.com/user-attachments/assets/c71c1074-6945-49ed-83a4-67fdb012dbeb)

In next release i make a better error handling for the upload things

**Comment by JasonLandbridge** [comment]
Thank you! I kept trying this token:

![image](https://github.com/user-attachments/assets/18c1468c-60d0-4ba4-88eb-0538cb59b3aa)

But after doing what you mentioned I successfully published my mod!

Thanks!

**Comment by TheBrutalX** [comment]
You're welcome!
I'm happy for your release! 🥳
I need to specify that in readme, is my mistake
